server:
  port: ${PORT:0}

spring:
  banner:
    image:
      location: banner.txt
  application:
    name: ms-cart
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': true
    show-sql: true


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
